Add network-type to subnet
adfinis-sygroup/foreman-yml pull request #45
Opened 2017-03-13 13:24 UTC by andreabettich

The import and dump supports the field network-type which can be IPv4 or IPv6.
This will fix #32

2017-03-13 13:31 UTC, jovandeginste commented
Long time ago, I guess this is ok :-)

2017-03-13 13:37 UTC, andreabettich commented
Yes, sorry about that. I hope the time of a respond and fix/implement will be a litte faster from now on.

2017-03-13 13:48 UTC, karras commented on config/example.yml
> +      network_type: IPv4
Please `s/_/-/g` :)

2017-03-13 13:53 UTC, karras requested changes
Just one small remark regarding replacing the "_" with "-".

2017-03-13 13:59 UTC, andreabettich commented on config/example.yml
> +      network_type: IPv4
Changed it. Thanks :)

2017-04-21 12:10 UTC, andreabettich commented
@karras can we merge this?

2017-04-25 12:36 UTC, karras approved these changes

2017-04-25 12:36 UTC, merged